name: dotnet release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish SubdivX/SubdivX.csproj -c Release -o release
      - name: Pack
        uses: papeloto/action-zip@v1
        with:
          files: release/SubdivX.dll
          dest: SubdivX-${{ github.ref }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ github.workspace }}/SubdivX-${{ github.ref }}.zip
