name: dotnet release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "TAG_MESSAGE=git tag -l --format='%(contents:subject)' ${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish SubdivX/SubdivX.csproj -c Release -o release
      - name: Pack
        uses: papeloto/action-zip@v1
        with:
          files: release/SubdivX.dll
          dest: SubdivX-${{ env.RELEASE_VERSION }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ env.TAG_MESSAGE }}
          files: ${{ github.workspace }}/SubdivX-${{ env.RELEASE_VERSION }}.zip
